version: 2
updates:
- package-ecosystem: github-actions
  directory: '/{{ cookiecutter.repo_name }}/.github'
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: "chore(deps)"
